language: scala
sudo: required
dist: trusty
addons:
  apt:
    update: true

jdk:
  - oraclejdk8

script:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
  - export PATH=~/bin/mill:$PATH
  - ./mill geny.__.test

cache:
  directories:
    - $HOME/.coursier
